### PR TITLE
GT4Py / NDSL / Serialbox Tutorials

### PR DESCRIPTION
**Pull request by gmao-ckung**
Several Jupyter notebooks have been developed that step through a GT4Py and NDSL tutorial as well as Serialbox/serialization tutorials to extract data from Fortran into Python for porting and verification.

### CODE REVIEW

**Comment by FlorianDeconinck** [comment]
This is looking good. For the fortran #2 on reading serialize data, I wonder if we should jump over the serialbox API and just demonstrated the Translate test infrastructure?

**Comment by gmao-ckung** [comment]
I may be in the minority, but where can I see the Translate test infrastructure?

**Comment by FlorianDeconinck** [comment]
> I may be in the minority, but where can I see the Translate test infrastructure?

Good point, we haven't pull the system down to NDSL! It's in `pyFV3`/`pySHiELD` so we will need to refactor it out

**Comment by gmao-ckung** [comment]
Ok I will leave the translate tests pull to NDSL to the experts.

**Comment by FlorianDeconinck** [comment]
We are rebase-ing this

**Pull request closed without merging**
