### PR TITLE
 MultiModal metric threshold override

### PR DESCRIPTION
**Pull request by FlorianDeconinck**
**Description**
Add threshold overrides to the multimodal metric using the following yaml schema
```yaml
ComputeUwshcu:
  - backend: dace:cpu
    multimodal:
      mmr_relative_fraction: 1e-2
      mmr_absolute_eps: 1e-10 
      mmr_ulp_threshold: 10
```

**How Has This Been Tested?**
Locally on GEOS physics code

**Checklist:**
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] New check tests, if applicable, are included

### CODE REVIEW

**Comment by oelbert** [comment]
At this point it's probably useful to document the error thresholding and reporting behavior somewhere, like to explain what ulp_threshold means or why some tests use the threshold yamls vs setting `self._max_error`

**Comment by FlorianDeconinck** [comment]
> At this point it's probably useful to document the error thresholding and reporting behavior somewhere, like to explain what ulp_threshold means or why some tests use the threshold yamls vs setting `self._max_error`

There's some instruction in `pyFV3`. Let me unearth those, complete them and moved them here

**Comment by FlorianDeconinck** [comment]
Ping @oelbert / @fmalatino: this is blocking us

**Review by fmalatino — DISMISSED** [review]
lgtm

**Review by fmalatino — DISMISSED** [review]
lgtm

**Review by fmalatino — APPROVED** [review]

**Pull request merged**
